export const GET_ALL_WEATHER = "GET_ALL_WEATHER";
export const GET_ALL_WEATHER_FAILURE = "GET_ALL_WEATHER_FAILURE";
export const GET_ALL_WEATHER_REQUEST = "GET_ALL_WEATHER_REQUEST";
export const UPDATE_INDEX = "UPDATE_INDEX";
